### PR TITLE
AC characteristics label for period leader pointing wrong direction (Issue #311)

### PR DESCRIPTION
**Pull request by AlexHedley**
Updated image suggested in #311

Current repo image:

Alternating Current

To

Alternating Current

---
<details>
<summary>Issue Info</summary>

From:

Alternating Current

To:

Alternating Current

</details>

### CODE REVIEW

**Comment by adrianstevens** [comment]
Great catch - looks like the Voltage label got rotated in the updated version

**Comment by AlexHedley** [comment]
Ah hadn't seen that on the issue, I'll see if I can rotate it back and update the PR.

**Comment by AlexHedley** [comment]
@adrianstevens hopefully worked my magic in Inkscape.

**Comment by AlexHedley** [comment]
@patridge this should be good to merge too.

**Comment by adrianstevens** [comment]
thx @AlexHedley !

**Pull request merged**
