### PR TITLE
API docs publishing DocFx CI

### LINKED ISSUE #440: docfx migration
Sadly, our Jenkins server died, RIP. The scripts for generating the docs have been [migrated to actions](https://github.com/WildernessLabs/Documentation/blob/main/.github/workflows/jekyll-beta.yml), but the API docs are sadly outdated. Here's the script from the Jenkins job:
```
cd Documentation
cd docfx
docfx docfx.json
(cat .\docs\api\Meadow\toc.html) | % { $_ -replace ">Meadow.Peripherals.", ">" } > .\docs\api\Meadow\toc.html
(cat .\docs\api\Meadow.Foundation\toc.html) | % { $_ -replace ">Meadow.Foundation.", ">" } > .\docs\api\Meadow.Foundation\toc.html
(cat .\docs\api\Meadow.Foundation\toc.html) | % { $_ -replace ">/a>", ">Meadow.Foundation</a>" } > .\docs\api\Meadow.Foundation\toc.html
cd ../docs
bundle install
bundle exec jekyll build
cp ../docfx/docs ./_site -r
aws s3 sync _site s3://developer.wildernesslabs.co --delete
```
(The jekyll portion isn't needed)

For this to work, Meadow and Meadow.Foudation repos need to be pulled as siblings.

### PR DESCRIPTION
**Pull request by CartBlanche**
Fixes #440

## Risk and recovery

* If something goes horribly wrong and it accidentally wipes out the current beta-develop API docs, we can copy the /api folder from production back over top of beta-develop with the help of someone with AWS access.
* If something goes super-extra horribly wrong and it accidentally wipes out all of beta-develop's docs content entirely somehow, we can run the existing beta docs publish Action to restore regular docs, and then run the above AWS copy back from production.

## Implementation details

* Deployment of API docs will only happen on manual Action trigger, since most content changes will be dependent on the code repos rather than the docs repo. With this latest if and on conditionals in place to limit to manual workflow_dispatch triggers, we shouldn't see any new content published immediately with the merge to develop. Prior to that, it would have technically run all the code repo cloning, build, and DocFX content build without actually publishing. (Maybe we do want content builds to run to see any code build or DocFX build errors before trying a manual publish, though.)
* The current version does not publish the API docs for Meadow.Foundation.Peripherals/Displays.WinForms because it requires a Windows build host that isn't compatible with the AWS publish Action we are using ([Ubuntu-only, not even macOS allowed](https://github.com/jakejarvis/s3-sync-action/pull/81)).
* We still don't have a system to handle deleting abandoned, deleted, or originals of moved files. The AWS Action we use offers a --delete option, but it is only documented at the bucket level, both in the Action and in the official AWS Sync docs. We are deploy to a sub-folder, so I don't want to risk deleting regular docs when deploying just API docs. After some more testing, we can figure out what we need to use.
* We updated the TOC handling for the additional Meadow.Foundation.* repos that wasn't present in the old pre-GitHub Actions implementation.

### CODE REVIEW

**Comment by CartBlanche** [comment]
@lamebrain As Meadow is a private repo, looks like we might need another PAT to be able to check it out in this CI.

**Comment by patridge** [comment]
> @lamebrain As Meadow is a private repo, looks like we might need another PAT to be able to check it out in this CI.

I don't have permission to see them. Did we ever get this token generated and in GH secrets under `secrets.CI_ACCESS_TOKEN`?

**Comment by CartBlanche** [comment]
@patridge the token is no longer the issue, because the repo wouldn't have checked out. I suppose the thing to do is to do exactly the same checkouts etc as the CI script and to then run docfx locally to see if we can replicate the failure and take it from there.

**Comment by patridge** [comment]
I'm no longer seeing Actions run on the PR in draft mode, and not seeing any way to run Actions manually anymore. I'm going to try switching to Ready for review to see if the Action will run that way. If not, I'll toggle back to draft.

**Comment by patridge** [comment]
Didn't trigger Actions. Toggling back to draft.

**Comment by patridge** [comment]
> Didn't trigger Actions. Toggling back to draft.

I lied. I don't appear to have permission to do that anymore. It's staying in ready to review, but hopefully the title keeps anyone from merging it.

**Review by patridge — APPROVED** [review]

**Review by adrianstevens — APPROVED** [review]

**Pull request merged**
